# Generated by Django 4.1.7 on 2023-03-14 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbrain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='session_id',
            new_name='chat_id',
        ),
    ]
