# Generated by Django 4.1.7 on 2023-03-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbrain', '0003_alter_chat_chat_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatbot',
        ),
    ]
